import { LegalPage, type LegalSection } from "@/components/LegalPage";

const sections: LegalSection[] = [
  {
    title: "Agreement to Terms",
    body: [
      "These Terms of Service (\"Terms\") govern your access to and use of CopyForge, an AI-powered copywriting tool provided as an online service (the \"Service\"). By creating an account, using the Service as a visitor, or purchasing credits, you agree to be bound by these Terms.",
      "If you are using the Service on behalf of a company or organization, you represent that you have authority to bind that entity to these Terms.",
    ],
  },
  {
    title: "The Service",
    body: [
      "CopyForge generates marketing copy (advertisements, captions, video scripts, and sales emails) from briefings you provide, using artificial intelligence. The Service is a tool that assists your work; it does not replace your professional judgment.",
      "We may add, change, or remove features at any time. We may also suspend or discontinue the Service, with reasonable notice where practical.",
    ],
  },
  {
    title: "Accounts and Authentication",
    body: [
      "You can use CopyForge with a passwordless email account (via one-time codes sent to your email) or as an anonymous visitor. You are responsible for maintaining access to your email inbox and for all activity that occurs under your session.",
      "One person or entity per account. You may not share your session, resell access to the Service, or use automated means to create accounts in bulk.",
    ],
  },
  {
    title: "Acceptable Use",
    body: [
      "You agree not to use the Service to create content that:",
    ],
    bullets: [
      "Is illegal, fraudulent, or deceptive, including scams and phishing.",
      "Infringes the intellectual property, privacy, or other rights of others.",
      "Contains malware or is designed to harm systems or users.",
      "Targets minors with inappropriate content.",
      "Promotes hate, harassment, or violence against individuals or groups.",
      "You also agree not to bypass credit limits, daily generation limits, or rate limits, or use automated means to abuse the Service.",
    ],
  },
  {
    title: "Credits and Payments",
    body: [
      "The Service uses a credit system: one credit is consumed per copy generation. Credits are granted through the free welcome package (after email verification) or purchased through PayPal or other supported payment methods.",
      "Purchased credits are prepaid and do not expire. Free welcome credits are subject to the daily generation limit and abuse protections described in the Service. We may adjust credit pricing and packaging, but changes will not reduce credits you have already purchased.",
      "Payments are processed by PayPal. By purchasing, you agree to PayPal's terms in addition to these Terms. Where a payment is reversed, charged back, or flagged as fraudulent, we may suspend the associated account and recover the corresponding credits.",
    ],
  },
  {
    title: "Daily Generation Limits",
    body: [
      "To protect service quality and prevent abuse, the Service applies a daily limit on copy generations per user (currently 10 generations per day), in addition to your total credit balance. The limit resets daily. Attempts to circumvent it through multiple accounts or automated requests may result in suspension.",
    ],
  },
  {
    title: "AI-Generated Content and Your Responsibility",
    body: [
      "Copy generated by the Service is produced by AI and may contain inaccuracies. You are responsible for reviewing all output before using it, and for ensuring that any claims, offers, prices, or statements in published marketing comply with the laws and advertising regulations that apply to you and your audience.",
      "The Service attempts to avoid inventing product facts, statistics, testimonials, or guarantees, but you must verify factual claims before publishing. You are solely responsible for how you use the generated copy.",
    ],
  },
  {
    title: "Intellectual Property",
    body: [
      "You own the briefings you submit and the copy you generate with the Service, to the extent permitted by law. You grant us a limited license to process that content solely to operate the Service (generate, store in your history, and display it to you).",
      "The CopyForge name, interface, code, prompts, and underlying AI integrations remain the property of the Service Operator. You may not copy or reuse them to build a competing product.",
    ],
  },
  {
    title: "Disclaimer of Warranties",
    body: [
      "The Service is provided \"as is\" and \"as available\", without warranties of any kind, whether express or implied, including merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that generated content will meet your commercial expectations.",
    ],
  },
  {
    title: "Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, the Service Operator shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenue, data, or business opportunities, arising from your use of or inability to use the Service.",
      "Our total aggregate liability for any claim relating to the Service is limited to the amount you paid to us in the 12 months preceding the claim, or US$50, whichever is greater.",
    ],
  },
  {
    title: "Termination",
    body: [
      "You may stop using the Service at any time. We may suspend or terminate your access if you breach these Terms, abuse the credit or generation systems, or create risk or legal exposure for us.",
      "Upon termination for your breach, remaining credits may be forfeited where the breach is material. Sections that by their nature should survive termination (intellectual property, disclaimers, liability limits) will survive.",
    ],
  },
  {
    title: "Changes to These Terms",
    body: [
      "We may update these Terms as the Service evolves. The current version is always available on this page with its effective date. Material changes will be announced on the Service where practical. Continued use after changes take effect constitutes acceptance.",
    ],
  },
  {
    title: "Contact",
    body: [
      "Questions about these Terms can be sent to the support address linked at the bottom of this page.",
    ],
  },
];

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      version="v1.0"
      updated="Last updated: September 2026"
      sections={sections}
    />
  );
}
